[[Geant4_julia]]
arch = "aarch64"
git-tree-sha1 = "939b6357dced5715d6acf7e29f0d6e7c4ec0906a"
julia_version = "1.10.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "23075ce74e1a845c8173ba6654d5fc103cddf690d25f5a470f4baf40829ead45"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
git-tree-sha1 = "37b48ed19a00d55bb358a2a658c813dd06595b7c"
julia_version = "1.11.1"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "219203e9e51303a2a56ddd17e2d406b8a86ea977e626f17b0e94449f106306ff"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
git-tree-sha1 = "8c8f74c7baff814f12f92031c18cd746f9eebea0"
julia_version = "1.12.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "e1ba1d1f511c9c4f445885b3ab356a3e846d9e7c1c7c940712ba7070cb4dbec5"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
git-tree-sha1 = "22bd885e44c42bc676e776c2c9c97c8483af7605"
julia_version = "1.13.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "f0a2f7ec04c854b449f55e6e393a0f9a1fb64683f09b1d862e359cfe68f0405a"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
git-tree-sha1 = "c308a07acf04958f0bb631b7d01f86492f42693a"
julia_version = "1.14.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "30c394817e0c599ea26747472ae4a0e64ce4fb0f03572991a238a1bea44dc0ea"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.aarch64-apple-darwin-julia_version+1.14.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef2624a725c222397e5aed88c84a699443e69b2c"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "5d7283a63ad0db72c3609c96ade7bbbb5f857e97360090095a958e4898b6246c"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bea26e6e42867ea220769cbcf909240f21f30636"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "5b9986d5ac098f5cf3c1577776657840e833306c33c596ec099c1c025f427a71"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54645d17996c7581e488407a1594c1d718b03730"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "48629df5d1c0f96075ee4138406ca799fdc6e3663fd1196dc334703492a4af18"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac7846eae7a2b828c17c1794f73dda992d84d234"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "8bccb64c34d0b91762ee10cc6684fccbc932fd0d8bb848d6b46709c2ed4a2053"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5f196988763ba6ebe8357f6ef3e79b8d052ba0c"
julia_version = "1.14.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "71c35a0774c1fa187179c6c323f5b55f632a988ea35ee5985c86c4398cd84a4c"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.14.0.tar.gz"
[[Geant4_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12cd6dad1edb663eacb3e57826c38278fc13ceef"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "4d9eec2d91d436104236c8693e6c5d7d2fe06610b12ff3f41899679d9d924f33"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d915a5397290f7e531280d7acdf21b4d2147a2ce"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "26cf3a014d5e3272620706883a148508c122145c7ae52c24a35e310f97f79146"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.powerpc64le-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d384f6ec133d7807ccc3984354604d287254238c"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "388e150419971ce84c95659c9931d983d033522a1e6d3fae9b7d3ca48f65866b"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.powerpc64le-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c965da4ff3ad05a294e93c9dd655241fe1dd2f0d"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "d57c751312c88aadae74fdd6c39ed62477893df5a4cabf42f1f494942144690d"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.powerpc64le-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4541bc573bb7116c912b17863d758772b6f5e788"
julia_version = "1.14.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "30382adaf46035f2d0197f5b42c91b0f24e2165baa8edd86ca5960837ad8ddb6"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.powerpc64le-linux-gnu-cxx11-julia_version+1.14.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
git-tree-sha1 = "27ae4bd43d77a949cb6f9de89d66e63f168b4a3a"
julia_version = "1.10.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "b6ed7617a3c54d0764e091c8a28621e259bfd169851d63c160ae9b0959902c19"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
git-tree-sha1 = "090140420eb40b3fa3a294c6faddf165a93fb611"
julia_version = "1.11.1"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "49c22fe4950b2f332f25c00ab2f7f3b6a6000e80783632ff965add545945cc2f"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
git-tree-sha1 = "7c7adbc632e822d21abe80ded9b1cdfbbfd5024e"
julia_version = "1.12.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "1dfed22aef97786b75c6c28b4ad032a828091b27c98921ed226103385d819c0a"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
git-tree-sha1 = "84ba13a9a3936620cfb79b8ad41afdabfca57a2a"
julia_version = "1.13.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "a66532b06eb194ea3194792dda26ea28b82b3dc924d67863568000882761f85c"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
git-tree-sha1 = "04a45c1546ccb0f2216a46e29113fea8194f934b"
julia_version = "1.14.0"
os = "macos"

    [[Geant4_julia.download]]
    sha256 = "ac4935381fdc29974cd4159b934357678543d8a8a2e6513342f86ab785b7470b"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-apple-darwin-julia_version+1.14.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b10f65031289eeffa1ad16a9f0672ae1ea068e5"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "d0f2c6557fa11689e80686ed02972bed66f8152ca9747e8ac848d2821fa8bf98"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cca958c724ab219726beb187a36b04f4406c9be6"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "c039cba37b4e06b3a1e1ffb86214851852b75f734765cbeda94586f71d7e2267"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7afcca248a6214e4c602bd4cbea2333a022e7fb"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "8432aa4a48c74c2e58b73c3533011aa5f5bd3fcca49bce510fa4c84c17d7c948"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c6816dbe347212a2cff7629db35b2bcf0b1e620"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "c942ee4c197f63db1ec00a17252dbafe742c015ed1c1c4e29fea612e5440786d"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d4d7ec64af22daf9a7f1b91ed9d4486fbd62f21"
julia_version = "1.14.0"
libc = "glibc"
os = "linux"

    [[Geant4_julia.download]]
    sha256 = "5be07b133e72579d78cc161feba8edaa23cd571725344c41cb7f9e2e44223196"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.14.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c84f4246243a0dc813b24d9e8dce0790a8c3105"
julia_version = "1.10.0"
os = "windows"

    [[Geant4_julia.download]]
    sha256 = "28e9ae6dca1a5c0da34768c2db91451bbf0d566f6eecddbd8c2e4e1eb53576dc"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7704b755f157bfba0742940d634816318de76b44"
julia_version = "1.11.1"
os = "windows"

    [[Geant4_julia.download]]
    sha256 = "59ac52de20cb45da736a619fd520e4af46793fb4f02c4868b913db906e56ca91"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9cb9c44436026ec34ab20e0594f366b957c156e"
julia_version = "1.12.0"
os = "windows"

    [[Geant4_julia.download]]
    sha256 = "e5dd3a3dfa47f90972ef5346bec1ad71dc0714fb955ee60de7cecfea2534454a"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c969dd4b6f75004d03bce8fb6733de5bef2fc54"
julia_version = "1.13.0"
os = "windows"

    [[Geant4_julia.download]]
    sha256 = "8c974efecaf915e01aa3a60671b50ed90fbf654e9ce22f4af4281713e3bdac9e"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
[[Geant4_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27e4955c579359c5729216bd37e8b0f9211508b6"
julia_version = "1.14.0"
os = "windows"

    [[Geant4_julia.download]]
    sha256 = "d03dfd90dd7dca7e14bd05ce163630d86eef34dc835a0d4629c6cd99b0037ea0"
    url = "https://github.com/JuliaBinaryWrappers/Geant4_julia_jll.jl/releases/download/Geant4_julia-v0.4.0+0/Geant4_julia.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.14.0.tar.gz"
